name: Perplexity Report

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht
  push:
    branches:
      - main

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Perplexity Report
        uses: perplexity/app-action@v1
        with:
          report_type: daily
